extension_dir="C:\Users\dhaka\Desktop\45-days-task-wise\runtime\php\ext"
extension=pdo_mysql
extension=mysqli
session.save_path="C:\Users\dhaka\AppData\Local\Temp"
date.timezone=Asia/Kolkata
extension=pdo_sqlite
extension=sqlite3
